"""initial

Revision ID: 28bcb522653b
Revises: 
Create Date: 2026-05-18 00:28:34.945675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28bcb522653b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_rate_limits',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_hash', sa.String(length=255), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('send_count', sa.Integer(), nullable=False),
    sa.Column('verify_attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_scan_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('qr_campaign_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source_code', sa.String(length=50), nullable=True),
    sa.Column('anonymous_session_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=255), nullable=True),
    sa.Column('is_likely_bot', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_settings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('restaurant_name', sa.String(length=200), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('external_ordering_url', sa.Text(), nullable=True),
    sa.Column('external_ordering_provider', sa.String(length=50), nullable=True),
    sa.Column('allow_order_without_signup', sa.Boolean(), nullable=False),
    sa.Column('default_reward_template_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('privacy_contact_email', sa.String(length=255), nullable=True),
    sa.Column('support_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_templates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code_prefix', sa.String(length=10), nullable=False),
    sa.Column('reward_type', sa.String(length=20), nullable=False),
    sa.Column('reward_value', sa.Integer(), nullable=False),
    sa.Column('min_order_cents', sa.Integer(), nullable=True),
    sa.Column('valid_days', sa.Integer(), nullable=False),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('external_order_redirects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reward_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source_code', sa.String(length=50), nullable=True),
    sa.Column('qr_campaign_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('destination_url', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('anonymous_session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('import_type', sa.String(length=30), nullable=False),
    sa.Column('uploaded_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sender_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('recipient_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_campaigns',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reward_template_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('landing_headline', sa.String(length=200), nullable=True),
    sa.Column('landing_subtitle', sa.String(length=300), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('rewards',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reward_template_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=True),
    sa.Column('qr_campaign_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redemption_source', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reward_template_id'], ['reward_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('signup_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=True),
    sa.Column('qr_campaign_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('signup_method', sa.String(length=30), nullable=False),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification_preferences',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sms_transactional_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('email_marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('consent_source', sa.String(length=50), nullable=True),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('short_links',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('destination_url', sa.Text(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reward_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('qr_campaign_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_links')
    op.drop_table('user_notification_preferences')
    op.drop_table('signup_events')
    op.drop_table('rewards')
    op.drop_table('refresh_tokens')
    op.drop_table('qr_campaigns')
    op.drop_table('notifications')
    op.drop_table('import_batches')
    op.drop_table('idempotency_keys')
    op.drop_table('external_order_redirects')
    op.drop_table('users')
    op.drop_table('reward_templates')
    op.drop_table('restaurant_settings')
    op.drop_table('qr_scan_events')
    op.drop_table('otp_rate_limits')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
