"""cart and reward uniqueness indexes

Revision ID: 465b5ea911c5
Revises: afb3c47d7a9b
Create Date: 2026-06-28 00:19:01.058050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465b5ea911c5'
down_revision: Union[str, None] = 'afb3c47d7a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cart_items_cart_menu', 'cart_items', ['cart_id', 'menu_item_id'])
    op.create_index('uq_carts_one_active_per_user', 'carts', ['user_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_index('uq_rewards_one_issued_per_user_template', 'rewards', ['user_id', 'reward_template_id'], unique=True, postgresql_where=sa.text("status = 'issued'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_rewards_one_issued_per_user_template', table_name='rewards', postgresql_where=sa.text("status = 'issued'"))
    op.drop_index('uq_carts_one_active_per_user', table_name='carts', postgresql_where=sa.text('is_active'))
    op.drop_constraint('uq_cart_items_cart_menu', 'cart_items', type_='unique')
    # ### end Alembic commands ###
