"""restaurant_settings.reward_sms_template (PRD-12 S7)

Revision ID: 8853d6bb2f22
Revises: e51ff52ecb86
Create Date: 2026-06-28 13:03:47.066748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8853d6bb2f22'
down_revision: Union[str, None] = 'e51ff52ecb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_settings', sa.Column('reward_sms_template', sa.String(length=320), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_settings', 'reward_sms_template')
    # ### end Alembic commands ###
