"""restaurant_settings copy/legal/locale/storefront (PRD-12 S3/S6/S9)

Revision ID: c9cd9d76b723
Revises: cb03587a01bf
Create Date: 2026-06-28 12:15:02.716397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9cd9d76b723'
down_revision: Union[str, None] = 'cb03587a01bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_settings', sa.Column('tagline', sa.String(length=300), nullable=True))
    op.add_column('restaurant_settings', sa.Column('reward_success_copy', sa.String(length=300), nullable=True))
    op.add_column('restaurant_settings', sa.Column('otp_sms_template', sa.String(length=320), nullable=True))
    op.add_column('restaurant_settings', sa.Column('legal_name', sa.String(length=200), nullable=True))
    op.add_column('restaurant_settings', sa.Column('business_mailing_address', sa.String(length=300), nullable=True))
    op.add_column('restaurant_settings', sa.Column('languages', sa.String(length=100), nullable=True))
    op.add_column('restaurant_settings', sa.Column('storefront_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_settings', 'storefront_enabled')
    op.drop_column('restaurant_settings', 'languages')
    op.drop_column('restaurant_settings', 'business_mailing_address')
    op.drop_column('restaurant_settings', 'legal_name')
    op.drop_column('restaurant_settings', 'otp_sms_template')
    op.drop_column('restaurant_settings', 'reward_success_copy')
    op.drop_column('restaurant_settings', 'tagline')
    # ### end Alembic commands ###
