"""restaurant_settings display fields (PRD-12 S8)

Revision ID: cb03587a01bf
Revises: feefeb3ca874
Create Date: 2026-06-28 01:50:51.149116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb03587a01bf'
down_revision: Union[str, None] = 'feefeb3ca874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_settings', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('restaurant_settings', sa.Column('contact_phone', sa.String(length=30), nullable=True))
    op.add_column('restaurant_settings', sa.Column('hours_json', sa.Text(), nullable=True))
    op.add_column('restaurant_settings', sa.Column('pickup_estimate', sa.String(length=80), nullable=True))
    op.add_column('restaurant_settings', sa.Column('tax_rate', sa.Float(), nullable=True))
    op.add_column('restaurant_settings', sa.Column('currency_symbol', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_settings', 'currency_symbol')
    op.drop_column('restaurant_settings', 'tax_rate')
    op.drop_column('restaurant_settings', 'pickup_estimate')
    op.drop_column('restaurant_settings', 'hours_json')
    op.drop_column('restaurant_settings', 'contact_phone')
    op.drop_column('restaurant_settings', 'address')
    # ### end Alembic commands ###
