"""restaurant_settings public_domain

Revision ID: feefeb3ca874
Revises: 465b5ea911c5
Create Date: 2026-06-28 00:36:27.307040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feefeb3ca874'
down_revision: Union[str, None] = '465b5ea911c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_settings', sa.Column('public_domain', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_settings', 'public_domain')
    # ### end Alembic commands ###
